"0","set.seed(231)"
"0","data = read.csv('data/titanic.csv')"
"2","cannot open file 'data/titanic.csv': No such file or directory"
"2","Error in file(file, ""rt"") : cannot open the connection
"
